# Generated by Django 6.0.3 on 2026-04-19 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cam_number', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rule', models.CharField(max_length=240)),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.camera')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.user')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.user'),
        ),
    ]
